#------------------------------------------------------------------------------
# TravisCI configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
matrix:
    include:
        - os: osx
          osx_image:
          - xcode7.3
before_install:
    - sudo ./setup.sh
before_script:
    - mkdir build
    - cd build
    - cmake .. -DGUI=0
script:
    - make
