#------------------------------------------------------------------------------
# TravisCI configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
branches:
    except:
        - /develop-v/
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=Debug
          env: ZIP_SUFFIX=ubuntu-trusty
        - os: osx
          osx_image: beta-xcode6.2
          env: TRAVIS_BUILD_TYPE=Debug
          env: ZIP_SUFFIX=osx-mavericks
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=Debug
          env: ZIP_SUFFIX=osx-yosemite
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=Debug
          env: ZIP_SUFFIX=osx-elcapitan
git:
    depth: 2
install:
    - ./install_deps.sh
before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE
    - make -j2
    - mkdir zip    
    - cp bench/bench zip/
    - cp eth/eth zip/
    - cp ethkey/ethkey zip/
    - cp ethminer/ethminer zip/
    - cp ethvm/ethvm zip/
    - cp libdevcore/*.dylib zip/
    - cp libdevcore/*.so zip/
    - cp libdevcrypto/*.dylib zip/
    - cp libdevcrypto/*.so zip/
    - cp libethash/*.dylib zip/
    - cp libethash/*.so zip/
    - cp libethash-cl/*.dylib zip/
    - cp libethash-cl/*.so zip/
    - cp libethashseal/*.dylib zip/
    - cp libethashseal/*.so zip/
    - cp libethcore/*.dylib zip/
    - cp libethcore/*.so zip/
    - cp libethereum/*.dylib zip/
    - cp libethereum/*.so zip/
    - cp libevm/*.dylib zip/
    - cp libevm/*.so zip/
    - cp libevmcore/*.dylib zip/
    - cp libevmcore/*.so zip/
    - cp libp2p/*.dylib zip/
    - cp libp2p/*.so zip/
    - cp libweb3jsonrpc/*.dylib zip/
    - cp libweb3jsonrpc/*.so zip/
    - cp libwebthree/*.dylib zip/
    - cp libwebthree/*.so zip/
    - cp libwhisper/*.dylib zip/
    - cp libwhisper/*.so zip/
    - cp rlp/rlp zip/
    - cp test/libethereum/testeth zip/
    - cp test/libweb3core/testweb3core zip/
    - cp test/webthree/testweb3 zip/
    - PATH_FIX_COMMAND_FOR_linux=""
    - PATH_FIX_COMMAND_FOR_osx="python ../homebrew/fix_homebrew_paths_in_standalone_zip.py zip/"
    - PATH_FIX_COMMAND_EXPRESSION_NAME=PATH_FIX_COMMAND_FOR_$TRAVIS_OS_NAME
    - PATH_FIX_COMMAND=$PATH_FIX_COMMAND_EXPRESSION_NAME
    - eval \$$PATH_FIX_COMMAND
    - zip -j $TRAVIS_BUILD_DIR/cpp-ethereum-develop-$ZIP_SUFFIX.zip zip/*    
script:
    - cd $TRAVIS_BUILD_DIR/..
    - git clone https://github.com/ethereum/tests.git
    - export ETHEREUM_TEST_PATH=$(pwd)/tests/
    - cd $TRAVIS_BUILD_DIR
    # Re-add unit-tests here when possible!
deploy:
    provider: releases
    api_key:
        secure: HHcAWFjVNwf8b83KVQnEa172Eo7aur+scVCq4BzgPDXnF+v4GDXT7PAaXyWBwIyrFoIJduPCojsiIBP8QZwtjaKgnywnREjaLc0syTCLSeUHcp/+jPRdickvfgHJWG06sU7ZST8/HnGmoOqV/BUlGhHiqma1oJfGEJ6aaG4oza77ZYAxLPxwq9NOuTHVGJwlphcfeevcU3F0C/mxDEEMEz66lDolp4DCP5L4muHlrOCZ+HSjRwz5/anVNVWNO/nM1I0wmI2TRAS0RPzwClVD8iiGJHhZ/WdgenG4nosBG9UQjd/56LLKI25bIJijz/tpe89pCRUJtMYtcXR5C7w8Is05a1GMedBAiT7Bu35qHbpxJeqcw26DJL4U3+IeHfymXpK/E3RAj16bj+mtxxYSEzaae7obCm1rDA1LnPTI94kAea2ZNOUucDK5FaROX/uBXk422xrQTdJpEpg4TLa7GmQGdtyJC0OnzaOTXWg87lbVMq1PndDLE3STqXT5J/wj/WfUtXlN38x9aX7wwrmyCXY3WJ1zzShAgRO9YjRRosMBkahGDj5l75w9KX8yW3C5txcxjPVGSxQIl+bv9FPrBJmU1WOOPYQlHm92JQJus8BXXQCuhg3mEsZQfmGpgrS82NUB15V1nZB3xCXniKcKnQirzbRXLg8wjlPbT9DKGbc=
    file: cpp-ethereum-develop-$ZIP_SUFFIX.zip
    skip_cleanup: true
    on:
        repo: bobsummerwill/cpp-ethereum
        branch: merge_repos
