#------------------------------------------------------------------------------
# TravisCI configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
os: osx
osx_image: xcode7.3
before_install:
- ./setup.sh
before_script:
- mkdir build
- cd build
- cmake ..
script: make eth ethminer ethkey
