#------------------------------------------------------------------------------
# TravisCI configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=Debug
          env: ZIP_SUFFIX=ubuntu-trusty
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=Debug
          env: ZIP_SUFFIX=osx-yosemite
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=Debug
          env: ZIP_SUFFIX=osx-elcapitan
git:
    depth: 2
branches:
    except:
        - /cpp-ethereum-develop-windows/
before_install:
    - ./install_deps.sh
before_script:
    - cd ..
    - git clone https://github.com/ethereum/tests.git
    - export ETHEREUM_TEST_PATH=$(pwd)/tests/
    - cd cpp-ethereum
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE
script:
    - make -j2
    
    # -j is "junk paths", because we don't want any directory substructure in the output ZIP.
    - zip -j cpp-ethereum-$ZIP_SUFFIX.zip bench/bench eth/eth ethkey/ethkey ethminer/ethminer ethvm/ethvm libdevcore/*.dylib libdevcore/*.so libdevcrypto/*.dylib libdevcrypto/*.so libethash/*.dylib libethash/*.so libethash-cl/*.dylib libethash-cl/*.so libethashseal/*.dylib libethashseal/*.so libethcore/*.dylib libethcore/*.so libethereum/*.dylib libethereum/*.so libevm/*.dylib libevm/*.so libevmcore/*.dylib libevmcore/*.so libp2p/*.dylib libp2p/*.so libweb3jsonrpc/*.dylib libweb3jsonrpc/*.so libwebthree/*.dylib libwebthree/*.so libwhisper/*.dylib libwhisper/*.so rlp/rlp test/libethereum/testeth test/libweb3core/testweb3core test/webthree/testweb3
deploy:
    provider: releases
    api_key:
        secure: Mb0k9yRCMlA+cFfTdiYbNfMjQJpWBRNqMMo7U8EBMXZCX0xWrAQDzM2PMfZev32qXTKDw/b4vmNOEy96L5bKng6wTl95QWMR7gghabr0C1nV4d057NcnhpTAJLKE1ODKCD4s+qraUbtc9Ghg0ENZsCTWxCgtK9igJs9kxSasXl2oambW+11F5VWht+oDSlkevpIy0XcuEpYUQJhO4BlJfEU0n9v65I4JJkbowLsdFSCVwRlw2jRUkpLwowGnDn5RJBl+aqtzvMRnKXNqaZWOztAw3oc0/zgp4NddrGJRJH+Tb7O+Uii6u/RSFYVb8HW3n+8jAYd5M3lOhrYHvhBwPBqWecrMk0FWzsVY+45NyzfMYjcj6jZOldUF+bZA16UxI/a367qUd8MhM2dJr9whfDQtd3Z5uS27gASSf7h987SjV7lp2Ok3QViFBWDi6MqWnlMq5lZzMGXGXiYvoB+rkw5ktzm3tvR4WIiGEK4V3X5/3lFS4Y0MN9B1YFNudPQ/byeawcXQHNsvSTsBCehJ3+KDpvjwQLGTup0lMK0hbglI0MichBmCqz0aAAimSyZQBgg8RQBA/elTyZSM1G8pUugjly3/E9T09x65iwhff37Zr868gvMtKre97tD+i0KbimRJCZHPW5iN9BIYhwMbLY2g6qX+Nu1KMU+i7TBXAAw=
    file: cpp-ethereum-$ZIP_SUFFIX.zip
    skip_cleanup: true
    on:
        repo: bobsummerwill/cpp-ethereum
        branch: merge_repos
