#------------------------------------------------------------------------------
# TravisCI configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
before_install:
    - sudo apt-add-repository -y ppa:george-edison55/cmake-3.x
    - sudo apt-get -y update
    - sudo apt-get -y install cmake
    
    - sudo apt-get -y install language-pack-en-base
    - sudo dpkg-reconfigure locales
    - sudo apt-get -y install software-properties-common
    
    - sudo add-apt-repository -y "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main"
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get -y update
    - sudo apt-get -y remove llvm-3.5-dev
    - sudo apt-get -y install llvm-3.7-dev
    
    - sudo add-apt-repository -y ppa:ethereum/ethereum-qt
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
    - sudo apt-get -y update
    
    - sudo apt-get -y install build-essential git libboost-all-dev libedit-dev libgmp-dev libleveldb-dev libminiupnpc-dev libcurl4-openssl-dev libcryptopp-dev libmicrohttpd-dev libjsoncpp-dev libjson-rpc-cpp-dev libz-dev opencl-headers
before_script:
    - mkdir build
    - cd build
    - cmake ..
script:
    - make eth ethminer ethkey
