#------------------------------------------------------------------------------
# TravisCI configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=Debug
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
git:
    depth: 2
before_install:
    - ./setup.sh
before_script:
    - mkdir build
    - cd build
    - cmake .. -DGUI=0 -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE
script:
    - make
