#------------------------------------------------------------------------------
# Appveyor configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# TODO - Address the hardcoded paths in this file.
# See https://github.com/ethereum/webthree-umbrella/issues/625.
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

os: Visual Studio 2015
configuration:
    - Debug
install:
    - git submodule update --init --recursive
    - cmake -P deps\install_deps.cmake
before_build:
    - cd ..
    - git clone https://github.com/ethereum/tests.git
    - cd cpp-ethereum
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" ..
build_script:
    - msbuild C:\projects\cpp-ethereum\build\cpp-ethereum.sln
test_script:
#    - cd C:\projects\cpp-ethereum\build\test\libethereum\test\Debug
#    - testeth.exe
#    - cd C:\projects\cpp-ethereum\build\test\libweb3core\test\Debug
#    - testweb3core.exe
    - set ETHEREUM_TEST_PATH=C:\projects\tests
    - cd C:\projects\cpp-ethereum\build\test\webthree\test\Debug
    - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvcp140.dll" .
    - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvcr140.dll" .
    - copy C:\projects\cpp-ethereum\deps\install\x64\bin\libcurl.dll" .
    - copy C:\projects\cpp-ethereum\deps\install\x64\bin\libmicrohttpd-dll.dll" .
    - copy C:\projects\cpp-ethereum\deps\install\x64\bin\OpenCL.dll" .
    - testweb3.exe
