#------------------------------------------------------------------------------
# Appveyor configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# TODO - Address the hardcoded paths in this file.
# See https://github.com/ethereum/webthree-umbrella/issues/625.
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

os: Visual Studio 2015
configuration:
    - Debug
install:
    - git submodule update --init --recursive
    - cmake -P deps\install_deps.cmake
    - set ETHEREUM_DEPS_PATH=%APPVEYOR_BUILD_FOLDER%\deps\install
before_build:
    - cd ..
    - git clone https://github.com/ethereum/tests.git
    - set ETHEREUM_TEST_PATH=%APPVEYOR_BUILD_FOLDER%\..\tests
    - cd cpp-ethereum
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" ..
build_script:
    - msbuild %APPVEYOR_BUILD_FOLDER%\build\cpp-ethereum.sln
    - cd %APPVEYOR_BUILD_FOLDER%\build\eth
    - 7z a cpp-ethereum.zip Debug\eth.exe "%VCINSTALLDIR%\redist\x86\Microsoft.VC140.CRT\msvc*.dll" %ETHEREUM_DEPS_PATH%\x64\bin\libcurl.dll %ETHEREUM_DEPS_PATH%\x64\bin\libmicrohttpd-dll.dll %ETHEREUM_DEPS_PATH%\win64\bin\OpenCL.dll
test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\build\test\libethereum\test\Debug
    - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvc*.dll" .
    - copy %ETHEREUM_DEPS_PATH%\x64\bin\libcurl.dll .
    - copy %ETHEREUM_DEPS_PATH%\x64\bin\libmicrohttpd-dll.dll .
    - testeth.exe

#    - cd %APPVEYOR_BUILD_FOLDER%\build\test\libweb3core\test\Debug
#    - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvc*.dll" .
#    - copy %ETHEREUM_DEPS_PATH%\x64\bin\libcurl.dll .
#    - copy %ETHEREUM_DEPS_PATH%\x64\bin\libmicrohttpd-dll.dll .
#    - testweb3core.exe
#
    - cd %APPVEYOR_BUILD_FOLDER%\build\test\webthree\test\Debug
    - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvc*.dll" .
    - copy %ETHEREUM_DEPS_PATH%\x64\bin\libcurl.dll .
    - copy %ETHEREUM_DEPS_PATH%\x64\bin\libmicrohttpd-dll.dll .
    - copy %ETHEREUM_DEPS_PATH%\win64\bin\OpenCL.dll .
    - testweb3.exe
artifacts:
    - path: C:\projects\cpp-ethereum\build\eth\cpp-ethereum.zip
      name: cpp-ethereum-zip
deploy:
    release: cpp-ethereum-appveyor-v$(appveyor_build_version)
    description: 'Automated Appveyor release of cpp-ethereum'
    provider: GitHub
    auth_token:
        secure: yukM9mHUbzuZSS5WSBLKSW0yGJerJEqAXkFhDhSHBBcKJE7GAryjQsdO9Kxh3yRv
    artifact: cpp-ethereum-zip
    on:
        branch: develop
