#------------------------------------------------------------------------------
# Appveyor configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

install:
- extdep/getstuff.bat
before_build:
- mkdir build
- cd build
- cmake -G "Visual Studio 12 2013 Win64" ..
build:
  project: build/cpp-ethereum.sln
