#------------------------------------------------------------------------------
# Appveyor configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# TODO - We are explicitly enabling EVMJIT here for Windows, because it is
# globally disabled by default to work around unresolved LLVM build issues
# for Ubuntu.  See https://github.com/ethereum/webthree-umbrella/issues/549.
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

os: Visual Studio 2015
configuration:
    - Debug
install:
    - git submodule update --init --recursive
    - cmake -P deps\install_deps.cmake
before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" .. -DEVMJIT=On
build_script:
    - msbuild C:\projects\cpp-ethereum\build\cpp-ethereum.sln
test_script:
    - cd C:\projects\cpp-ethereum\build\test\libethereum\test\Debug
    - testeth.exe
    - cd C:\projects\cpp-ethereum\build\test\libweb3core\test\Debug
    - testweb3core.exe
    - cd C:\projects\cpp-ethereum\build\test\libwebthree\test\Debug
    - testweb3.exe
