codecov:
  branch: develop
coverage:
  range: 50...100
  notify:
    gitter:
      default:
        threshold: 0
        url: https://gitter.im/ethereum/cpp-ethereum-development
  status:
    patch:
      default:
        target: 25
    project:
      default:
        target: auto
    changes:
      default:
        enabled: no
comment:
  layout: "reach, diff, flags, files, footer"
flags:
  alltests:
    joined: false
ignore:
  - test/tools/fuzzTesting/fuzzHelper.cpp